# Build and deploy action for the github page

name: CI

on:
  # Triggers the workflow on push
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-22.04
    name: Jupyterbook build process
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Install required apt packages 
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential python3.10 python3-pip python3-dev git git-lfs time wget imagemagick

      - name: Checkout LFS objects because checkout action is stupid?
        run: git lfs checkout

      - name: Install Python dependecies
        run: |
          pip3.10 install --upgrade pip
          pip3.10 install jupyter-book sphinx_revealjs sphinx_proof matplotlib numpy jupytext pytest regex

      - name: Build pages
        run: jb build info1-book --builder html

      - name: Upload page artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'info1-book/_build/html/'


  # Deploy job
  deploy:
    needs: build
    
    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
